// src/app.ts
import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import cookieParser from "cookie-parser";

// src/middleware/errorHandler.ts
var AppError = class extends Error {
  statusCode;
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;
  }
};
var errorHandler = (err, _req, res, _next) => {
  if (err instanceof AppError) {
    return res.status(err.statusCode).json({ success: false, message: err.message });
  }
  console.error("Unhandled error:", err);
  res.status(500).json({ success: false, message: "Internal server error" });
};

// src/features/auth/auth.routes.ts
import { Router } from "express";

// src/utils/response.ts
var sendSuccess = (res, data, message = "Success", statusCode = 200) => {
  res.status(statusCode).json({ success: true, message, data });
};
var sendError = (res, message, statusCode = 400, errorDetails) => {
  res.status(statusCode).json({ success: false, message, errorDetails });
};

// src/features/auth/auth.validation.ts
import { z } from "zod";
var registerSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
  name: z.string().min(1),
  phone: z.string().optional(),
  role: z.enum(["CUSTOMER", "PROVIDER"])
});
var loginSchema = z.object({
  email: z.string().email(),
  password: z.string()
});
var updateProfileSchema = z.object({
  name: z.string().min(1).optional(),
  phone: z.string().optional()
});
var updatePasswordSchema = z.object({
  currentPassword: z.string().min(1),
  newPassword: z.string().min(6)
});

// src/features/auth/auth.service.ts
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

// src/utils/prisma.ts
import "dotenv/config";
import pg from "pg";

// src/generated/prisma/client.ts
import * as path from "node:path";
import { fileURLToPath } from "node:url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.8.0",
  "engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum Role {\n  CUSTOMER\n  PROVIDER\n  ADMIN\n}\n\nenum RentalStatus {\n  PLACED\n  CONFIRMED\n  PAID\n  PICKED_UP\n  RETURNED\n  CANCELLED\n}\n\nenum PaymentMethod {\n  STRIPE\n}\n\nenum PaymentStatus {\n  PENDING\n  COMPLETED\n  FAILED\n}\n\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  password  String\n  name      String\n  phone     String?\n  role      Role     @default(CUSTOMER)\n  isActive  Boolean  @default(true)\n  createdAt DateTime @default(now())\n\n  rentals  RentalOrder[]\n  payments Payment[]\n  reviews  Review[]\n  gear     GearItem[]\n\n  @@map("users")\n}\n\nmodel Category {\n  id          String   @id @default(cuid())\n  name        String   @unique\n  description String?\n  createdAt   DateTime @default(now())\n\n  gear GearItem[]\n\n  @@map("categories")\n}\n\nmodel GearItem {\n  id          String   @id @default(cuid())\n  name        String\n  description String\n  brand       String?\n  pricePerDay Float\n  quantity    Int\n  available   Boolean  @default(true)\n  createdAt   DateTime @default(now())\n\n  categoryId String\n  category   Category @relation(fields: [categoryId], references: [id])\n\n  providerId String\n  provider   User   @relation(fields: [providerId], references: [id])\n\n  rentalItems RentalItem[]\n  reviews     Review[]\n\n  @@map("gear_items")\n}\n\nmodel RentalOrder {\n  id          String       @id @default(cuid())\n  startDate   DateTime\n  endDate     DateTime\n  status      RentalStatus @default(PLACED)\n  totalAmount Float\n  note        String?\n  createdAt   DateTime     @default(now())\n\n  customerId String\n  customer   User   @relation(fields: [customerId], references: [id])\n\n  rentalItems RentalItem[]\n  payments    Payment[]\n\n  @@map("rental_orders")\n}\n\nmodel RentalItem {\n  id       String @id @default(cuid())\n  quantity Int\n\n  rentalOrderId String\n  rentalOrder   RentalOrder @relation(fields: [rentalOrderId], references: [id], onDelete: Cascade)\n\n  gearItemId String\n  gearItem   GearItem @relation(fields: [gearItemId], references: [id])\n\n  @@map("rental_items")\n}\n\nmodel Payment {\n  id            String        @id @default(cuid())\n  transactionId String        @unique\n  amount        Float\n  method        PaymentMethod @default(STRIPE)\n  status        PaymentStatus @default(PENDING)\n  paidAt        DateTime?\n  createdAt     DateTime      @default(now())\n\n  stripePaymentIntentId String?\n  stripeClientSecret    String?\n\n  rentalOrderId String\n  rentalOrder   RentalOrder @relation(fields: [rentalOrderId], references: [id])\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id])\n\n  @@map("payments")\n}\n\nmodel Review {\n  id        String   @id @default(cuid())\n  rating    Int\n  comment   String?\n  createdAt DateTime @default(now())\n\n  gearItemId String\n  gearItem   GearItem @relation(fields: [gearItemId], references: [id])\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id])\n\n  @@unique([userId, gearItemId])\n  @@map("reviews")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"isActive","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"rentals","kind":"object","type":"RentalOrder","relationName":"RentalOrderToUser"},{"name":"payments","kind":"object","type":"Payment","relationName":"PaymentToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"gear","kind":"object","type":"GearItem","relationName":"GearItemToUser"}],"dbName":"users"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"gear","kind":"object","type":"GearItem","relationName":"CategoryToGearItem"}],"dbName":"categories"},"GearItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"brand","kind":"scalar","type":"String"},{"name":"pricePerDay","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"available","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToGearItem"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"provider","kind":"object","type":"User","relationName":"GearItemToUser"},{"name":"rentalItems","kind":"object","type":"RentalItem","relationName":"GearItemToRentalItem"},{"name":"reviews","kind":"object","type":"Review","relationName":"GearItemToReview"}],"dbName":"gear_items"},"RentalOrder":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"startDate","kind":"scalar","type":"DateTime"},{"name":"endDate","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"RentalStatus"},{"name":"totalAmount","kind":"scalar","type":"Float"},{"name":"note","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"RentalOrderToUser"},{"name":"rentalItems","kind":"object","type":"RentalItem","relationName":"RentalItemToRentalOrder"},{"name":"payments","kind":"object","type":"Payment","relationName":"PaymentToRentalOrder"}],"dbName":"rental_orders"},"RentalItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"rentalOrderId","kind":"scalar","type":"String"},{"name":"rentalOrder","kind":"object","type":"RentalOrder","relationName":"RentalItemToRentalOrder"},{"name":"gearItemId","kind":"scalar","type":"String"},{"name":"gearItem","kind":"object","type":"GearItem","relationName":"GearItemToRentalItem"}],"dbName":"rental_items"},"Payment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"transactionId","kind":"scalar","type":"String"},{"name":"amount","kind":"scalar","type":"Float"},{"name":"method","kind":"enum","type":"PaymentMethod"},{"name":"status","kind":"enum","type":"PaymentStatus"},{"name":"paidAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"stripePaymentIntentId","kind":"scalar","type":"String"},{"name":"stripeClientSecret","kind":"scalar","type":"String"},{"name":"rentalOrderId","kind":"scalar","type":"String"},{"name":"rentalOrder","kind":"object","type":"RentalOrder","relationName":"PaymentToRentalOrder"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"PaymentToUser"}],"dbName":"payments"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"gearItemId","kind":"scalar","type":"String"},{"name":"gearItem","kind":"object","type":"GearItem","relationName":"GearItemToReview"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"}],"dbName":"reviews"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","customer","rentalOrder","gear","_count","category","provider","rentalItems","gearItem","user","reviews","payments","rentals","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","GearItem.findUnique","GearItem.findUniqueOrThrow","GearItem.findFirst","GearItem.findFirstOrThrow","GearItem.findMany","GearItem.createOne","GearItem.createMany","GearItem.createManyAndReturn","GearItem.updateOne","GearItem.updateMany","GearItem.updateManyAndReturn","GearItem.upsertOne","GearItem.deleteOne","GearItem.deleteMany","_avg","_sum","GearItem.groupBy","GearItem.aggregate","RentalOrder.findUnique","RentalOrder.findUniqueOrThrow","RentalOrder.findFirst","RentalOrder.findFirstOrThrow","RentalOrder.findMany","RentalOrder.createOne","RentalOrder.createMany","RentalOrder.createManyAndReturn","RentalOrder.updateOne","RentalOrder.updateMany","RentalOrder.updateManyAndReturn","RentalOrder.upsertOne","RentalOrder.deleteOne","RentalOrder.deleteMany","RentalOrder.groupBy","RentalOrder.aggregate","RentalItem.findUnique","RentalItem.findUniqueOrThrow","RentalItem.findFirst","RentalItem.findFirstOrThrow","RentalItem.findMany","RentalItem.createOne","RentalItem.createMany","RentalItem.createManyAndReturn","RentalItem.updateOne","RentalItem.updateMany","RentalItem.updateManyAndReturn","RentalItem.upsertOne","RentalItem.deleteOne","RentalItem.deleteMany","RentalItem.groupBy","RentalItem.aggregate","Payment.findUnique","Payment.findUniqueOrThrow","Payment.findFirst","Payment.findFirstOrThrow","Payment.findMany","Payment.createOne","Payment.createMany","Payment.createManyAndReturn","Payment.updateOne","Payment.updateMany","Payment.updateManyAndReturn","Payment.upsertOne","Payment.deleteOne","Payment.deleteMany","Payment.groupBy","Payment.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","AND","OR","NOT","id","rating","comment","createdAt","gearItemId","userId","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","transactionId","amount","PaymentMethod","method","PaymentStatus","status","paidAt","stripePaymentIntentId","stripeClientSecret","rentalOrderId","quantity","startDate","endDate","RentalStatus","totalAmount","note","customerId","name","description","brand","pricePerDay","available","categoryId","providerId","every","some","none","email","password","phone","Role","role","isActive","userId_gearItemId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "9ANHcA8FAADrAQAgDAAA9QEAIA0AAPQBACAOAADzAQAghwEAAPABADCIAQAAJQAQiQEAAPABADCKAQEAAAABjQFAAOoBACGsAQEA6AEAIbYBAQAAAAG3AQEA6AEAIbgBAQDpAQAhugEAAPEBugEiuwEgAPIBACEBAAAAAQAgDgMAAPwBACAJAACDAgAgDQAA9AEAIIcBAACFAgAwiAEAAAMAEIkBAACFAgAwigEBAOgBACGNAUAA6gEAIaABAACGAqkBIqYBQADqAQAhpwFAAOoBACGpAQgA9wEAIaoBAQDpAQAhqwEBAOgBACEEAwAAuwMAIAkAAL4DACANAAC4AwAgqgEAAIcCACAOAwAA_AEAIAkAAIMCACANAAD0AQAghwEAAIUCADCIAQAAAwAQiQEAAIUCADCKAQEAAAABjQFAAOoBACGgAQAAhgKpASKmAUAA6gEAIacBQADqAQAhqQEIAPcBACGqAQEA6QEAIasBAQDoAQAhAwAAAAMAIAEAAAQAMAIAAAUAIAkEAAD7AQAgCgAAgAIAIIcBAACEAgAwiAEAAAcAEIkBAACEAgAwigEBAOgBACGOAQEA6AEAIaQBAQDoAQAhpQECAP8BACECBAAAugMAIAoAALwDACAJBAAA-wEAIAoAAIACACCHAQAAhAIAMIgBAAAHABCJAQAAhAIAMIoBAQAAAAGOAQEA6AEAIaQBAQDoAQAhpQECAP8BACEDAAAABwAgAQAACAAwAgAACQAgEQcAAIICACAIAAD8AQAgCQAAgwIAIAwAAPUBACCHAQAAgQIAMIgBAAALABCJAQAAgQIAMIoBAQDoAQAhjQFAAOoBACGlAQIA_wEAIawBAQDoAQAhrQEBAOgBACGuAQEA6QEAIa8BCAD3AQAhsAEgAPIBACGxAQEA6AEAIbIBAQDoAQAhBQcAAL0DACAIAAC7AwAgCQAAvgMAIAwAALkDACCuAQAAhwIAIBEHAACCAgAgCAAA_AEAIAkAAIMCACAMAAD1AQAghwEAAIECADCIAQAACwAQiQEAAIECADCKAQEAAAABjQFAAOoBACGlAQIA_wEAIawBAQDoAQAhrQEBAOgBACGuAQEA6QEAIa8BCAD3AQAhsAEgAPIBACGxAQEA6AEAIbIBAQDoAQAhAwAAAAsAIAEAAAwAMAIAAA0AIAEAAAALACADAAAABwAgAQAACAAwAgAACQAgCwoAAIACACALAAD8AQAghwEAAP4BADCIAQAAEQAQiQEAAP4BADCKAQEA6AEAIYsBAgD_AQAhjAEBAOkBACGNAUAA6gEAIY4BAQDoAQAhjwEBAOgBACEDCgAAvAMAIAsAALsDACCMAQAAhwIAIAwKAACAAgAgCwAA_AEAIIcBAAD-AQAwiAEAABEAEIkBAAD-AQAwigEBAAAAAYsBAgD_AQAhjAEBAOkBACGNAUAA6gEAIY4BAQDoAQAhjwEBAOgBACG8AQAA_QEAIAMAAAARACABAAASADACAAATACABAAAABwAgAQAAABEAIBAEAAD7AQAgCwAA_AEAIIcBAAD2AQAwiAEAABcAEIkBAAD2AQAwigEBAOgBACGNAUAA6gEAIY8BAQDoAQAhmwEBAOgBACGcAQgA9wEAIZ4BAAD4AZ4BIqABAAD5AaABIqEBQAD6AQAhogEBAOkBACGjAQEA6QEAIaQBAQDoAQAhBQQAALoDACALAAC7AwAgoQEAAIcCACCiAQAAhwIAIKMBAACHAgAgEAQAAPsBACALAAD8AQAghwEAAPYBADCIAQAAFwAQiQEAAPYBADCKAQEAAAABjQFAAOoBACGPAQEA6AEAIZsBAQAAAAGcAQgA9wEAIZ4BAAD4AZ4BIqABAAD5AaABIqEBQAD6AQAhogEBAOkBACGjAQEA6QEAIaQBAQDoAQAhAwAAABcAIAEAABgAMAIAABkAIAEAAAAHACABAAAAFwAgAwAAABcAIAEAABgAMAIAABkAIAMAAAARACABAAASADACAAATACADAAAACwAgAQAADAAwAgAADQAgAQAAAAMAIAEAAAAXACABAAAAEQAgAQAAAAsAIAEAAAABACAPBQAA6wEAIAwAAPUBACANAAD0AQAgDgAA8wEAIIcBAADwAQAwiAEAACUAEIkBAADwAQAwigEBAOgBACGNAUAA6gEAIawBAQDoAQAhtgEBAOgBACG3AQEA6AEAIbgBAQDpAQAhugEAAPEBugEiuwEgAPIBACEFBQAAgwMAIAwAALkDACANAAC4AwAgDgAAtwMAILgBAACHAgAgAwAAACUAIAEAACYAMAIAAAEAIAMAAAAlACABAAAmADACAAABACADAAAAJQAgAQAAJgAwAgAAAQAgDAUAALYDACAMAAC1AwAgDQAAtAMAIA4AALMDACCKAQEAAAABjQFAAAAAAawBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG6AQAAALoBArsBIAAAAAEBFAAAKgAgCIoBAQAAAAGNAUAAAAABrAEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAboBAAAAugECuwEgAAAAAQEUAAAsADABFAAALAAwDAUAAIsDACAMAACKAwAgDQAAiQMAIA4AAIgDACCKAQEAjQIAIY0BQACQAgAhrAEBAI0CACG2AQEAjQIAIbcBAQCNAgAhuAEBAI8CACG6AQAAhwO6ASK7ASAA1AIAIQIAAAABACAUAAAvACAIigEBAI0CACGNAUAAkAIAIawBAQCNAgAhtgEBAI0CACG3AQEAjQIAIbgBAQCPAgAhugEAAIcDugEiuwEgANQCACECAAAAJQAgFAAAMQAgAgAAACUAIBQAADEAIAMAAAABACAbAAAqACAcAAAvACABAAAAAQAgAQAAACUAIAQGAACEAwAgIQAAhgMAICIAAIUDACC4AQAAhwIAIAuHAQAA7AEAMIgBAAA4ABCJAQAA7AEAMIoBAQDDAQAhjQFAAMYBACGsAQEAwwEAIbYBAQDDAQAhtwEBAMMBACG4AQEAxQEAIboBAADtAboBIrsBIADjAQAhAwAAACUAIAEAADcAMCAAADgAIAMAAAAlACABAAAmADACAAABACAIBQAA6wEAIIcBAADnAQAwiAEAAD4AEIkBAADnAQAwigEBAAAAAY0BQADqAQAhrAEBAAAAAa0BAQDpAQAhAQAAADsAIAEAAAA7ACAIBQAA6wEAIIcBAADnAQAwiAEAAD4AEIkBAADnAQAwigEBAOgBACGNAUAA6gEAIawBAQDoAQAhrQEBAOkBACECBQAAgwMAIK0BAACHAgAgAwAAAD4AIAEAAD8AMAIAADsAIAMAAAA-ACABAAA_ADACAAA7ACADAAAAPgAgAQAAPwAwAgAAOwAgBQUAAIIDACCKAQEAAAABjQFAAAAAAawBAQAAAAGtAQEAAAABARQAAEMAIASKAQEAAAABjQFAAAAAAawBAQAAAAGtAQEAAAABARQAAEUAMAEUAABFADAFBQAA9QIAIIoBAQCNAgAhjQFAAJACACGsAQEAjQIAIa0BAQCPAgAhAgAAADsAIBQAAEgAIASKAQEAjQIAIY0BQACQAgAhrAEBAI0CACGtAQEAjwIAIQIAAAA-ACAUAABKACACAAAAPgAgFAAASgAgAwAAADsAIBsAAEMAIBwAAEgAIAEAAAA7ACABAAAAPgAgBAYAAPICACAhAAD0AgAgIgAA8wIAIK0BAACHAgAgB4cBAADmAQAwiAEAAFEAEIkBAADmAQAwigEBAMMBACGNAUAAxgEAIawBAQDDAQAhrQEBAMUBACEDAAAAPgAgAQAAUAAwIAAAUQAgAwAAAD4AIAEAAD8AMAIAADsAIAEAAAANACABAAAADQAgAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAALACABAAAMADACAAANACADAAAACwAgAQAADAAwAgAADQAgDgcAAO4CACAIAADvAgAgCQAA8AIAIAwAAPECACCKAQEAAAABjQFAAAAAAaUBAgAAAAGsAQEAAAABrQEBAAAAAa4BAQAAAAGvAQgAAAABsAEgAAAAAbEBAQAAAAGyAQEAAAABARQAAFkAIAqKAQEAAAABjQFAAAAAAaUBAgAAAAGsAQEAAAABrQEBAAAAAa4BAQAAAAGvAQgAAAABsAEgAAAAAbEBAQAAAAGyAQEAAAABARQAAFsAMAEUAABbADAOBwAA1QIAIAgAANYCACAJAADXAgAgDAAA2AIAIIoBAQCNAgAhjQFAAJACACGlAQIAjgIAIawBAQCNAgAhrQEBAI0CACGuAQEAjwIAIa8BCACaAgAhsAEgANQCACGxAQEAjQIAIbIBAQCNAgAhAgAAAA0AIBQAAF4AIAqKAQEAjQIAIY0BQACQAgAhpQECAI4CACGsAQEAjQIAIa0BAQCNAgAhrgEBAI8CACGvAQgAmgIAIbABIADUAgAhsQEBAI0CACGyAQEAjQIAIQIAAAALACAUAABgACACAAAACwAgFAAAYAAgAwAAAA0AIBsAAFkAIBwAAF4AIAEAAAANACABAAAACwAgBgYAAM8CACAhAADSAgAgIgAA0QIAIEMAANACACBEAADTAgAgrgEAAIcCACANhwEAAOIBADCIAQAAZwAQiQEAAOIBADCKAQEAwwEAIY0BQADGAQAhpQECAMQBACGsAQEAwwEAIa0BAQDDAQAhrgEBAMUBACGvAQgA0gEAIbABIADjAQAhsQEBAMMBACGyAQEAwwEAIQMAAAALACABAABmADAgAABnACADAAAACwAgAQAADAAwAgAADQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACALAwAAzAIAIAkAAM0CACANAADOAgAgigEBAAAAAY0BQAAAAAGgAQAAAKkBAqYBQAAAAAGnAUAAAAABqQEIAAAAAaoBAQAAAAGrAQEAAAABARQAAG8AIAiKAQEAAAABjQFAAAAAAaABAAAAqQECpgFAAAAAAacBQAAAAAGpAQgAAAABqgEBAAAAAasBAQAAAAEBFAAAcQAwARQAAHEAMAsDAACxAgAgCQAAsgIAIA0AALMCACCKAQEAjQIAIY0BQACQAgAhoAEAALACqQEipgFAAJACACGnAUAAkAIAIakBCACaAgAhqgEBAI8CACGrAQEAjQIAIQIAAAAFACAUAAB0ACAIigEBAI0CACGNAUAAkAIAIaABAACwAqkBIqYBQACQAgAhpwFAAJACACGpAQgAmgIAIaoBAQCPAgAhqwEBAI0CACECAAAAAwAgFAAAdgAgAgAAAAMAIBQAAHYAIAMAAAAFACAbAABvACAcAAB0ACABAAAABQAgAQAAAAMAIAYGAACrAgAgIQAArgIAICIAAK0CACBDAACsAgAgRAAArwIAIKoBAACHAgAgC4cBAADeAQAwiAEAAH0AEIkBAADeAQAwigEBAMMBACGNAUAAxgEAIaABAADfAakBIqYBQADGAQAhpwFAAMYBACGpAQgA0gEAIaoBAQDFAQAhqwEBAMMBACEDAAAAAwAgAQAAfAAwIAAAfQAgAwAAAAMAIAEAAAQAMAIAAAUAIAEAAAAJACABAAAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgBgQAAKkCACAKAACqAgAgigEBAAAAAY4BAQAAAAGkAQEAAAABpQECAAAAAQEUAACFAQAgBIoBAQAAAAGOAQEAAAABpAEBAAAAAaUBAgAAAAEBFAAAhwEAMAEUAACHAQAwBgQAAKcCACAKAACoAgAgigEBAI0CACGOAQEAjQIAIaQBAQCNAgAhpQECAI4CACECAAAACQAgFAAAigEAIASKAQEAjQIAIY4BAQCNAgAhpAEBAI0CACGlAQIAjgIAIQIAAAAHACAUAACMAQAgAgAAAAcAIBQAAIwBACADAAAACQAgGwAAhQEAIBwAAIoBACABAAAACQAgAQAAAAcAIAUGAACiAgAgIQAApQIAICIAAKQCACBDAACjAgAgRAAApgIAIAeHAQAA3QEAMIgBAACTAQAQiQEAAN0BADCKAQEAwwEAIY4BAQDDAQAhpAEBAMMBACGlAQIAxAEAIQMAAAAHACABAACSAQAwIAAAkwEAIAMAAAAHACABAAAIADACAAAJACABAAAAGQAgAQAAABkAIAMAAAAXACABAAAYADACAAAZACADAAAAFwAgAQAAGAAwAgAAGQAgAwAAABcAIAEAABgAMAIAABkAIA0EAACgAgAgCwAAoQIAIIoBAQAAAAGNAUAAAAABjwEBAAAAAZsBAQAAAAGcAQgAAAABngEAAACeAQKgAQAAAKABAqEBQAAAAAGiAQEAAAABowEBAAAAAaQBAQAAAAEBFAAAmwEAIAuKAQEAAAABjQFAAAAAAY8BAQAAAAGbAQEAAAABnAEIAAAAAZ4BAAAAngECoAEAAACgAQKhAUAAAAABogEBAAAAAaMBAQAAAAGkAQEAAAABARQAAJ0BADABFAAAnQEAMA0EAACeAgAgCwAAnwIAIIoBAQCNAgAhjQFAAJACACGPAQEAjQIAIZsBAQCNAgAhnAEIAJoCACGeAQAAmwKeASKgAQAAnAKgASKhAUAAnQIAIaIBAQCPAgAhowEBAI8CACGkAQEAjQIAIQIAAAAZACAUAACgAQAgC4oBAQCNAgAhjQFAAJACACGPAQEAjQIAIZsBAQCNAgAhnAEIAJoCACGeAQAAmwKeASKgAQAAnAKgASKhAUAAnQIAIaIBAQCPAgAhowEBAI8CACGkAQEAjQIAIQIAAAAXACAUAACiAQAgAgAAABcAIBQAAKIBACADAAAAGQAgGwAAmwEAIBwAAKABACABAAAAGQAgAQAAABcAIAgGAACVAgAgIQAAmAIAICIAAJcCACBDAACWAgAgRAAAmQIAIKEBAACHAgAgogEAAIcCACCjAQAAhwIAIA6HAQAA0QEAMIgBAACpAQAQiQEAANEBADCKAQEAwwEAIY0BQADGAQAhjwEBAMMBACGbAQEAwwEAIZwBCADSAQAhngEAANMBngEioAEAANQBoAEioQFAANUBACGiAQEAxQEAIaMBAQDFAQAhpAEBAMMBACEDAAAAFwAgAQAAqAEAMCAAAKkBACADAAAAFwAgAQAAGAAwAgAAGQAgAQAAABMAIAEAAAATACADAAAAEQAgAQAAEgAwAgAAEwAgAwAAABEAIAEAABIAMAIAABMAIAMAAAARACABAAASADACAAATACAICgAAkwIAIAsAAJQCACCKAQEAAAABiwECAAAAAYwBAQAAAAGNAUAAAAABjgEBAAAAAY8BAQAAAAEBFAAAsQEAIAaKAQEAAAABiwECAAAAAYwBAQAAAAGNAUAAAAABjgEBAAAAAY8BAQAAAAEBFAAAswEAMAEUAACzAQAwCAoAAJECACALAACSAgAgigEBAI0CACGLAQIAjgIAIYwBAQCPAgAhjQFAAJACACGOAQEAjQIAIY8BAQCNAgAhAgAAABMAIBQAALYBACAGigEBAI0CACGLAQIAjgIAIYwBAQCPAgAhjQFAAJACACGOAQEAjQIAIY8BAQCNAgAhAgAAABEAIBQAALgBACACAAAAEQAgFAAAuAEAIAMAAAATACAbAACxAQAgHAAAtgEAIAEAAAATACABAAAAEQAgBgYAAIgCACAhAACLAgAgIgAAigIAIEMAAIkCACBEAACMAgAgjAEAAIcCACAJhwEAAMIBADCIAQAAvwEAEIkBAADCAQAwigEBAMMBACGLAQIAxAEAIYwBAQDFAQAhjQFAAMYBACGOAQEAwwEAIY8BAQDDAQAhAwAAABEAIAEAAL4BADAgAAC_AQAgAwAAABEAIAEAABIAMAIAABMAIAmHAQAAwgEAMIgBAAC_AQAQiQEAAMIBADCKAQEAwwEAIYsBAgDEAQAhjAEBAMUBACGNAUAAxgEAIY4BAQDDAQAhjwEBAMMBACEOBgAAyAEAICEAANABACAiAADQAQAgkAEBAAAAAZEBAQAAAASSAQEAAAAEkwEBAAAAAZQBAQAAAAGVAQEAAAABlgEBAAAAAZcBAQDPAQAhmAEBAAAAAZkBAQAAAAGaAQEAAAABDQYAAMgBACAhAADIAQAgIgAAyAEAIEMAAM4BACBEAADIAQAgkAECAAAAAZEBAgAAAASSAQIAAAAEkwECAAAAAZQBAgAAAAGVAQIAAAABlgECAAAAAZcBAgDNAQAhDgYAAMsBACAhAADMAQAgIgAAzAEAIJABAQAAAAGRAQEAAAAFkgEBAAAABZMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEAygEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQsGAADIAQAgIQAAyQEAICIAAMkBACCQAUAAAAABkQFAAAAABJIBQAAAAASTAUAAAAABlAFAAAAAAZUBQAAAAAGWAUAAAAABlwFAAMcBACELBgAAyAEAICEAAMkBACAiAADJAQAgkAFAAAAAAZEBQAAAAASSAUAAAAAEkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADHAQAhCJABAgAAAAGRAQIAAAAEkgECAAAABJMBAgAAAAGUAQIAAAABlQECAAAAAZYBAgAAAAGXAQIAyAEAIQiQAUAAAAABkQFAAAAABJIBQAAAAASTAUAAAAABlAFAAAAAAZUBQAAAAAGWAUAAAAABlwFAAMkBACEOBgAAywEAICEAAMwBACAiAADMAQAgkAEBAAAAAZEBAQAAAAWSAQEAAAAFkwEBAAAAAZQBAQAAAAGVAQEAAAABlgEBAAAAAZcBAQDKAQAhmAEBAAAAAZkBAQAAAAGaAQEAAAABCJABAgAAAAGRAQIAAAAFkgECAAAABZMBAgAAAAGUAQIAAAABlQECAAAAAZYBAgAAAAGXAQIAywEAIQuQAQEAAAABkQEBAAAABZIBAQAAAAWTAQEAAAABlAEBAAAAAZUBAQAAAAGWAQEAAAABlwEBAMwBACGYAQEAAAABmQEBAAAAAZoBAQAAAAENBgAAyAEAICEAAMgBACAiAADIAQAgQwAAzgEAIEQAAMgBACCQAQIAAAABkQECAAAABJIBAgAAAASTAQIAAAABlAECAAAAAZUBAgAAAAGWAQIAAAABlwECAM0BACEIkAEIAAAAAZEBCAAAAASSAQgAAAAEkwEIAAAAAZQBCAAAAAGVAQgAAAABlgEIAAAAAZcBCADOAQAhDgYAAMgBACAhAADQAQAgIgAA0AEAIJABAQAAAAGRAQEAAAAEkgEBAAAABJMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEAzwEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQuQAQEAAAABkQEBAAAABJIBAQAAAASTAQEAAAABlAEBAAAAAZUBAQAAAAGWAQEAAAABlwEBANABACGYAQEAAAABmQEBAAAAAZoBAQAAAAEOhwEAANEBADCIAQAAqQEAEIkBAADRAQAwigEBAMMBACGNAUAAxgEAIY8BAQDDAQAhmwEBAMMBACGcAQgA0gEAIZ4BAADTAZ4BIqABAADUAaABIqEBQADVAQAhogEBAMUBACGjAQEAxQEAIaQBAQDDAQAhDQYAAMgBACAhAADOAQAgIgAAzgEAIEMAAM4BACBEAADOAQAgkAEIAAAAAZEBCAAAAASSAQgAAAAEkwEIAAAAAZQBCAAAAAGVAQgAAAABlgEIAAAAAZcBCADcAQAhBwYAAMgBACAhAADbAQAgIgAA2wEAIJABAAAAngECkQEAAACeAQiSAQAAAJ4BCJcBAADaAZ4BIgcGAADIAQAgIQAA2QEAICIAANkBACCQAQAAAKABApEBAAAAoAEIkgEAAACgAQiXAQAA2AGgASILBgAAywEAICEAANcBACAiAADXAQAgkAFAAAAAAZEBQAAAAAWSAUAAAAAFkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADWAQAhCwYAAMsBACAhAADXAQAgIgAA1wEAIJABQAAAAAGRAUAAAAAFkgFAAAAABZMBQAAAAAGUAUAAAAABlQFAAAAAAZYBQAAAAAGXAUAA1gEAIQiQAUAAAAABkQFAAAAABZIBQAAAAAWTAUAAAAABlAFAAAAAAZUBQAAAAAGWAUAAAAABlwFAANcBACEHBgAAyAEAICEAANkBACAiAADZAQAgkAEAAACgAQKRAQAAAKABCJIBAAAAoAEIlwEAANgBoAEiBJABAAAAoAECkQEAAACgAQiSAQAAAKABCJcBAADZAaABIgcGAADIAQAgIQAA2wEAICIAANsBACCQAQAAAJ4BApEBAAAAngEIkgEAAACeAQiXAQAA2gGeASIEkAEAAACeAQKRAQAAAJ4BCJIBAAAAngEIlwEAANsBngEiDQYAAMgBACAhAADOAQAgIgAAzgEAIEMAAM4BACBEAADOAQAgkAEIAAAAAZEBCAAAAASSAQgAAAAEkwEIAAAAAZQBCAAAAAGVAQgAAAABlgEIAAAAAZcBCADcAQAhB4cBAADdAQAwiAEAAJMBABCJAQAA3QEAMIoBAQDDAQAhjgEBAMMBACGkAQEAwwEAIaUBAgDEAQAhC4cBAADeAQAwiAEAAH0AEIkBAADeAQAwigEBAMMBACGNAUAAxgEAIaABAADfAakBIqYBQADGAQAhpwFAAMYBACGpAQgA0gEAIaoBAQDFAQAhqwEBAMMBACEHBgAAyAEAICEAAOEBACAiAADhAQAgkAEAAACpAQKRAQAAAKkBCJIBAAAAqQEIlwEAAOABqQEiBwYAAMgBACAhAADhAQAgIgAA4QEAIJABAAAAqQECkQEAAACpAQiSAQAAAKkBCJcBAADgAakBIgSQAQAAAKkBApEBAAAAqQEIkgEAAACpAQiXAQAA4QGpASINhwEAAOIBADCIAQAAZwAQiQEAAOIBADCKAQEAwwEAIY0BQADGAQAhpQECAMQBACGsAQEAwwEAIa0BAQDDAQAhrgEBAMUBACGvAQgA0gEAIbABIADjAQAhsQEBAMMBACGyAQEAwwEAIQUGAADIAQAgIQAA5QEAICIAAOUBACCQASAAAAABlwEgAOQBACEFBgAAyAEAICEAAOUBACAiAADlAQAgkAEgAAAAAZcBIADkAQAhApABIAAAAAGXASAA5QEAIQeHAQAA5gEAMIgBAABRABCJAQAA5gEAMIoBAQDDAQAhjQFAAMYBACGsAQEAwwEAIa0BAQDFAQAhCAUAAOsBACCHAQAA5wEAMIgBAAA-ABCJAQAA5wEAMIoBAQDoAQAhjQFAAOoBACGsAQEA6AEAIa0BAQDpAQAhC5ABAQAAAAGRAQEAAAAEkgEBAAAABJMBAQAAAAGUAQEAAAABlQEBAAAAAZYBAQAAAAGXAQEA0AEAIZgBAQAAAAGZAQEAAAABmgEBAAAAAQuQAQEAAAABkQEBAAAABZIBAQAAAAWTAQEAAAABlAEBAAAAAZUBAQAAAAGWAQEAAAABlwEBAMwBACGYAQEAAAABmQEBAAAAAZoBAQAAAAEIkAFAAAAAAZEBQAAAAASSAUAAAAAEkwFAAAAAAZQBQAAAAAGVAUAAAAABlgFAAAAAAZcBQADJAQAhA7MBAAALACC0AQAACwAgtQEAAAsAIAuHAQAA7AEAMIgBAAA4ABCJAQAA7AEAMIoBAQDDAQAhjQFAAMYBACGsAQEAwwEAIbYBAQDDAQAhtwEBAMMBACG4AQEAxQEAIboBAADtAboBIrsBIADjAQAhBwYAAMgBACAhAADvAQAgIgAA7wEAIJABAAAAugECkQEAAAC6AQiSAQAAALoBCJcBAADuAboBIgcGAADIAQAgIQAA7wEAICIAAO8BACCQAQAAALoBApEBAAAAugEIkgEAAAC6AQiXAQAA7gG6ASIEkAEAAAC6AQKRAQAAALoBCJIBAAAAugEIlwEAAO8BugEiDwUAAOsBACAMAAD1AQAgDQAA9AEAIA4AAPMBACCHAQAA8AEAMIgBAAAlABCJAQAA8AEAMIoBAQDoAQAhjQFAAOoBACGsAQEA6AEAIbYBAQDoAQAhtwEBAOgBACG4AQEA6QEAIboBAADxAboBIrsBIADyAQAhBJABAAAAugECkQEAAAC6AQiSAQAAALoBCJcBAADvAboBIgKQASAAAAABlwEgAOUBACEDswEAAAMAILQBAAADACC1AQAAAwAgA7MBAAAXACC0AQAAFwAgtQEAABcAIAOzAQAAEQAgtAEAABEAILUBAAARACAQBAAA-wEAIAsAAPwBACCHAQAA9gEAMIgBAAAXABCJAQAA9gEAMIoBAQDoAQAhjQFAAOoBACGPAQEA6AEAIZsBAQDoAQAhnAEIAPcBACGeAQAA-AGeASKgAQAA-QGgASKhAUAA-gEAIaIBAQDpAQAhowEBAOkBACGkAQEA6AEAIQiQAQgAAAABkQEIAAAABJIBCAAAAASTAQgAAAABlAEIAAAAAZUBCAAAAAGWAQgAAAABlwEIAM4BACEEkAEAAACeAQKRAQAAAJ4BCJIBAAAAngEIlwEAANsBngEiBJABAAAAoAECkQEAAACgAQiSAQAAAKABCJcBAADZAaABIgiQAUAAAAABkQFAAAAABZIBQAAAAAWTAUAAAAABlAFAAAAAAZUBQAAAAAGWAUAAAAABlwFAANcBACEQAwAA_AEAIAkAAIMCACANAAD0AQAghwEAAIUCADCIAQAAAwAQiQEAAIUCADCKAQEA6AEAIY0BQADqAQAhoAEAAIYCqQEipgFAAOoBACGnAUAA6gEAIakBCAD3AQAhqgEBAOkBACGrAQEA6AEAIb0BAAADACC-AQAAAwAgEQUAAOsBACAMAAD1AQAgDQAA9AEAIA4AAPMBACCHAQAA8AEAMIgBAAAlABCJAQAA8AEAMIoBAQDoAQAhjQFAAOoBACGsAQEA6AEAIbYBAQDoAQAhtwEBAOgBACG4AQEA6QEAIboBAADxAboBIrsBIADyAQAhvQEAACUAIL4BAAAlACACjgEBAAAAAY8BAQAAAAELCgAAgAIAIAsAAPwBACCHAQAA_gEAMIgBAAARABCJAQAA_gEAMIoBAQDoAQAhiwECAP8BACGMAQEA6QEAIY0BQADqAQAhjgEBAOgBACGPAQEA6AEAIQiQAQIAAAABkQECAAAABJIBAgAAAASTAQIAAAABlAECAAAAAZUBAgAAAAGWAQIAAAABlwECAMgBACETBwAAggIAIAgAAPwBACAJAACDAgAgDAAA9QEAIIcBAACBAgAwiAEAAAsAEIkBAACBAgAwigEBAOgBACGNAUAA6gEAIaUBAgD_AQAhrAEBAOgBACGtAQEA6AEAIa4BAQDpAQAhrwEIAPcBACGwASAA8gEAIbEBAQDoAQAhsgEBAOgBACG9AQAACwAgvgEAAAsAIBEHAACCAgAgCAAA_AEAIAkAAIMCACAMAAD1AQAghwEAAIECADCIAQAACwAQiQEAAIECADCKAQEA6AEAIY0BQADqAQAhpQECAP8BACGsAQEA6AEAIa0BAQDoAQAhrgEBAOkBACGvAQgA9wEAIbABIADyAQAhsQEBAOgBACGyAQEA6AEAIQoFAADrAQAghwEAAOcBADCIAQAAPgAQiQEAAOcBADCKAQEA6AEAIY0BQADqAQAhrAEBAOgBACGtAQEA6QEAIb0BAAA-ACC-AQAAPgAgA7MBAAAHACC0AQAABwAgtQEAAAcAIAkEAAD7AQAgCgAAgAIAIIcBAACEAgAwiAEAAAcAEIkBAACEAgAwigEBAOgBACGOAQEA6AEAIaQBAQDoAQAhpQECAP8BACEOAwAA_AEAIAkAAIMCACANAAD0AQAghwEAAIUCADCIAQAAAwAQiQEAAIUCADCKAQEA6AEAIY0BQADqAQAhoAEAAIYCqQEipgFAAOoBACGnAUAA6gEAIakBCAD3AQAhqgEBAOkBACGrAQEA6AEAIQSQAQAAAKkBApEBAAAAqQEIkgEAAACpAQiXAQAA4QGpASIAAAAAAAABwgEBAAAAAQXCAQIAAAAByAECAAAAAckBAgAAAAHKAQIAAAABywECAAAAAQHCAQEAAAABAcIBQAAAAAEFGwAA7QMAIBwAAPMDACC_AQAA7gMAIMABAADyAwAgxQEAAA0AIAUbAADrAwAgHAAA8AMAIL8BAADsAwAgwAEAAO8DACDFAQAAAQAgAxsAAO0DACC_AQAA7gMAIMUBAAANACADGwAA6wMAIL8BAADsAwAgxQEAAAEAIAAAAAAABcIBCAAAAAHIAQgAAAAByQEIAAAAAcoBCAAAAAHLAQgAAAABAcIBAAAAngECAcIBAAAAoAECAcIBQAAAAAEFGwAA4wMAIBwAAOkDACC_AQAA5AMAIMABAADoAwAgxQEAAAUAIAUbAADhAwAgHAAA5gMAIL8BAADiAwAgwAEAAOUDACDFAQAAAQAgAxsAAOMDACC_AQAA5AMAIMUBAAAFACADGwAA4QMAIL8BAADiAwAgxQEAAAEAIAAAAAAABRsAANkDACAcAADfAwAgvwEAANoDACDAAQAA3gMAIMUBAAAFACAFGwAA1wMAIBwAANwDACC_AQAA2AMAIMABAADbAwAgxQEAAA0AIAMbAADZAwAgvwEAANoDACDFAQAABQAgAxsAANcDACC_AQAA2AMAIMUBAAANACAAAAAAAAHCAQAAAKkBAgUbAADQAwAgHAAA1QMAIL8BAADRAwAgwAEAANQDACDFAQAAAQAgCxsAAMACADAcAADFAgAwvwEAAMECADDAAQAAwgIAMMEBAADDAgAgwgEAAMQCADDDAQAAxAIAMMQBAADEAgAwxQEAAMQCADDGAQAAxgIAMMcBAADHAgAwCxsAALQCADAcAAC5AgAwvwEAALUCADDAAQAAtgIAMMEBAAC3AgAgwgEAALgCADDDAQAAuAIAMMQBAAC4AgAwxQEAALgCADDGAQAAugIAMMcBAAC7AgAwCwsAAKECACCKAQEAAAABjQFAAAAAAY8BAQAAAAGbAQEAAAABnAEIAAAAAZ4BAAAAngECoAEAAACgAQKhAUAAAAABogEBAAAAAaMBAQAAAAECAAAAGQAgGwAAvwIAIAMAAAAZACAbAAC_AgAgHAAAvgIAIAEUAADTAwAwEAQAAPsBACALAAD8AQAghwEAAPYBADCIAQAAFwAQiQEAAPYBADCKAQEAAAABjQFAAOoBACGPAQEA6AEAIZsBAQAAAAGcAQgA9wEAIZ4BAAD4AZ4BIqABAAD5AaABIqEBQAD6AQAhogEBAOkBACGjAQEA6QEAIaQBAQDoAQAhAgAAABkAIBQAAL4CACACAAAAvAIAIBQAAL0CACAOhwEAALsCADCIAQAAvAIAEIkBAAC7AgAwigEBAOgBACGNAUAA6gEAIY8BAQDoAQAhmwEBAOgBACGcAQgA9wEAIZ4BAAD4AZ4BIqABAAD5AaABIqEBQAD6AQAhogEBAOkBACGjAQEA6QEAIaQBAQDoAQAhDocBAAC7AgAwiAEAALwCABCJAQAAuwIAMIoBAQDoAQAhjQFAAOoBACGPAQEA6AEAIZsBAQDoAQAhnAEIAPcBACGeAQAA-AGeASKgAQAA-QGgASKhAUAA-gEAIaIBAQDpAQAhowEBAOkBACGkAQEA6AEAIQqKAQEAjQIAIY0BQACQAgAhjwEBAI0CACGbAQEAjQIAIZwBCACaAgAhngEAAJsCngEioAEAAJwCoAEioQFAAJ0CACGiAQEAjwIAIaMBAQCPAgAhCwsAAJ8CACCKAQEAjQIAIY0BQACQAgAhjwEBAI0CACGbAQEAjQIAIZwBCACaAgAhngEAAJsCngEioAEAAJwCoAEioQFAAJ0CACGiAQEAjwIAIaMBAQCPAgAhCwsAAKECACCKAQEAAAABjQFAAAAAAY8BAQAAAAGbAQEAAAABnAEIAAAAAZ4BAAAAngECoAEAAACgAQKhAUAAAAABogEBAAAAAaMBAQAAAAEECgAAqgIAIIoBAQAAAAGOAQEAAAABpQECAAAAAQIAAAAJACAbAADLAgAgAwAAAAkAIBsAAMsCACAcAADKAgAgARQAANIDADAJBAAA-wEAIAoAAIACACCHAQAAhAIAMIgBAAAHABCJAQAAhAIAMIoBAQAAAAGOAQEA6AEAIaQBAQDoAQAhpQECAP8BACECAAAACQAgFAAAygIAIAIAAADIAgAgFAAAyQIAIAeHAQAAxwIAMIgBAADIAgAQiQEAAMcCADCKAQEA6AEAIY4BAQDoAQAhpAEBAOgBACGlAQIA_wEAIQeHAQAAxwIAMIgBAADIAgAQiQEAAMcCADCKAQEA6AEAIY4BAQDoAQAhpAEBAOgBACGlAQIA_wEAIQOKAQEAjQIAIY4BAQCNAgAhpQECAI4CACEECgAAqAIAIIoBAQCNAgAhjgEBAI0CACGlAQIAjgIAIQQKAACqAgAgigEBAAAAAY4BAQAAAAGlAQIAAAABAxsAANADACC_AQAA0QMAIMUBAAABACAEGwAAwAIAML8BAADBAgAwwQEAAMMCACDFAQAAxAIAMAQbAAC0AgAwvwEAALUCADDBAQAAtwIAIMUBAAC4AgAwAAAAAAABwgEgAAAAAQUbAADGAwAgHAAAzgMAIL8BAADHAwAgwAEAAM0DACDFAQAAOwAgBRsAAMQDACAcAADLAwAgvwEAAMUDACDAAQAAygMAIMUBAAABACALGwAA5QIAMBwAAOkCADC_AQAA5gIAMMABAADnAgAwwQEAAOgCACDCAQAAxAIAMMMBAADEAgAwxAEAAMQCADDFAQAAxAIAMMYBAADqAgAwxwEAAMcCADALGwAA2QIAMBwAAN4CADC_AQAA2gIAMMABAADbAgAwwQEAANwCACDCAQAA3QIAMMMBAADdAgAwxAEAAN0CADDFAQAA3QIAMMYBAADfAgAwxwEAAOACADAGCwAAlAIAIIoBAQAAAAGLAQIAAAABjAEBAAAAAY0BQAAAAAGPAQEAAAABAgAAABMAIBsAAOQCACADAAAAEwAgGwAA5AIAIBwAAOMCACABFAAAyQMAMAwKAACAAgAgCwAA_AEAIIcBAAD-AQAwiAEAABEAEIkBAAD-AQAwigEBAAAAAYsBAgD_AQAhjAEBAOkBACGNAUAA6gEAIY4BAQDoAQAhjwEBAOgBACG8AQAA_QEAIAIAAAATACAUAADjAgAgAgAAAOECACAUAADiAgAgCYcBAADgAgAwiAEAAOECABCJAQAA4AIAMIoBAQDoAQAhiwECAP8BACGMAQEA6QEAIY0BQADqAQAhjgEBAOgBACGPAQEA6AEAIQmHAQAA4AIAMIgBAADhAgAQiQEAAOACADCKAQEA6AEAIYsBAgD_AQAhjAEBAOkBACGNAUAA6gEAIY4BAQDoAQAhjwEBAOgBACEFigEBAI0CACGLAQIAjgIAIYwBAQCPAgAhjQFAAJACACGPAQEAjQIAIQYLAACSAgAgigEBAI0CACGLAQIAjgIAIYwBAQCPAgAhjQFAAJACACGPAQEAjQIAIQYLAACUAgAgigEBAAAAAYsBAgAAAAGMAQEAAAABjQFAAAAAAY8BAQAAAAEEBAAAqQIAIIoBAQAAAAGkAQEAAAABpQECAAAAAQIAAAAJACAbAADtAgAgAwAAAAkAIBsAAO0CACAcAADsAgAgARQAAMgDADACAAAACQAgFAAA7AIAIAIAAADIAgAgFAAA6wIAIAOKAQEAjQIAIaQBAQCNAgAhpQECAI4CACEEBAAApwIAIIoBAQCNAgAhpAEBAI0CACGlAQIAjgIAIQQEAACpAgAgigEBAAAAAaQBAQAAAAGlAQIAAAABAxsAAMYDACC_AQAAxwMAIMUBAAA7ACADGwAAxAMAIL8BAADFAwAgxQEAAAEAIAQbAADlAgAwvwEAAOYCADDBAQAA6AIAIMUBAADEAgAwBBsAANkCADC_AQAA2gIAMMEBAADcAgAgxQEAAN0CADAAAAALGwAA9gIAMBwAAPsCADC_AQAA9wIAMMABAAD4AgAwwQEAAPkCACDCAQAA-gIAMMMBAAD6AgAwxAEAAPoCADDFAQAA-gIAMMYBAAD8AgAwxwEAAP0CADAMCAAA7wIAIAkAAPACACAMAADxAgAgigEBAAAAAY0BQAAAAAGlAQIAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEIAAAAAbABIAAAAAGyAQEAAAABAgAAAA0AIBsAAIEDACADAAAADQAgGwAAgQMAIBwAAIADACABFAAAwwMAMBEHAACCAgAgCAAA_AEAIAkAAIMCACAMAAD1AQAghwEAAIECADCIAQAACwAQiQEAAIECADCKAQEAAAABjQFAAOoBACGlAQIA_wEAIawBAQDoAQAhrQEBAOgBACGuAQEA6QEAIa8BCAD3AQAhsAEgAPIBACGxAQEA6AEAIbIBAQDoAQAhAgAAAA0AIBQAAIADACACAAAA_gIAIBQAAP8CACANhwEAAP0CADCIAQAA_gIAEIkBAAD9AgAwigEBAOgBACGNAUAA6gEAIaUBAgD_AQAhrAEBAOgBACGtAQEA6AEAIa4BAQDpAQAhrwEIAPcBACGwASAA8gEAIbEBAQDoAQAhsgEBAOgBACENhwEAAP0CADCIAQAA_gIAEIkBAAD9AgAwigEBAOgBACGNAUAA6gEAIaUBAgD_AQAhrAEBAOgBACGtAQEA6AEAIa4BAQDpAQAhrwEIAPcBACGwASAA8gEAIbEBAQDoAQAhsgEBAOgBACEJigEBAI0CACGNAUAAkAIAIaUBAgCOAgAhrAEBAI0CACGtAQEAjQIAIa4BAQCPAgAhrwEIAJoCACGwASAA1AIAIbIBAQCNAgAhDAgAANYCACAJAADXAgAgDAAA2AIAIIoBAQCNAgAhjQFAAJACACGlAQIAjgIAIawBAQCNAgAhrQEBAI0CACGuAQEAjwIAIa8BCACaAgAhsAEgANQCACGyAQEAjQIAIQwIAADvAgAgCQAA8AIAIAwAAPECACCKAQEAAAABjQFAAAAAAaUBAgAAAAGsAQEAAAABrQEBAAAAAa4BAQAAAAGvAQgAAAABsAEgAAAAAbIBAQAAAAEEGwAA9gIAML8BAAD3AgAwwQEAAPkCACDFAQAA-gIAMAAAAAABwgEAAAC6AQILGwAApwMAMBwAAKwDADC_AQAAqAMAMMABAACpAwAwwQEAAKoDACDCAQAAqwMAMMMBAACrAwAwxAEAAKsDADDFAQAAqwMAMMYBAACtAwAwxwEAAK4DADALGwAAngMAMBwAAKIDADC_AQAAnwMAMMABAACgAwAwwQEAAKEDACDCAQAAuAIAMMMBAAC4AgAwxAEAALgCADDFAQAAuAIAMMYBAACjAwAwxwEAALsCADALGwAAlQMAMBwAAJkDADC_AQAAlgMAMMABAACXAwAwwQEAAJgDACDCAQAA3QIAMMMBAADdAgAwxAEAAN0CADDFAQAA3QIAMMYBAACaAwAwxwEAAOACADALGwAAjAMAMBwAAJADADC_AQAAjQMAMMABAACOAwAwwQEAAI8DACDCAQAA-gIAMMMBAAD6AgAwxAEAAPoCADDFAQAA-gIAMMYBAACRAwAwxwEAAP0CADAMBwAA7gIAIAkAAPACACAMAADxAgAgigEBAAAAAY0BQAAAAAGlAQIAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEIAAAAAbABIAAAAAGxAQEAAAABAgAAAA0AIBsAAJQDACADAAAADQAgGwAAlAMAIBwAAJMDACABFAAAwgMAMAIAAAANACAUAACTAwAgAgAAAP4CACAUAACSAwAgCYoBAQCNAgAhjQFAAJACACGlAQIAjgIAIawBAQCNAgAhrQEBAI0CACGuAQEAjwIAIa8BCACaAgAhsAEgANQCACGxAQEAjQIAIQwHAADVAgAgCQAA1wIAIAwAANgCACCKAQEAjQIAIY0BQACQAgAhpQECAI4CACGsAQEAjQIAIa0BAQCNAgAhrgEBAI8CACGvAQgAmgIAIbABIADUAgAhsQEBAI0CACEMBwAA7gIAIAkAAPACACAMAADxAgAgigEBAAAAAY0BQAAAAAGlAQIAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEIAAAAAbABIAAAAAGxAQEAAAABBgoAAJMCACCKAQEAAAABiwECAAAAAYwBAQAAAAGNAUAAAAABjgEBAAAAAQIAAAATACAbAACdAwAgAwAAABMAIBsAAJ0DACAcAACcAwAgARQAAMEDADACAAAAEwAgFAAAnAMAIAIAAADhAgAgFAAAmwMAIAWKAQEAjQIAIYsBAgCOAgAhjAEBAI8CACGNAUAAkAIAIY4BAQCNAgAhBgoAAJECACCKAQEAjQIAIYsBAgCOAgAhjAEBAI8CACGNAUAAkAIAIY4BAQCNAgAhBgoAAJMCACCKAQEAAAABiwECAAAAAYwBAQAAAAGNAUAAAAABjgEBAAAAAQsEAACgAgAgigEBAAAAAY0BQAAAAAGbAQEAAAABnAEIAAAAAZ4BAAAAngECoAEAAACgAQKhAUAAAAABogEBAAAAAaMBAQAAAAGkAQEAAAABAgAAABkAIBsAAKYDACADAAAAGQAgGwAApgMAIBwAAKUDACABFAAAwAMAMAIAAAAZACAUAAClAwAgAgAAALwCACAUAACkAwAgCooBAQCNAgAhjQFAAJACACGbAQEAjQIAIZwBCACaAgAhngEAAJsCngEioAEAAJwCoAEioQFAAJ0CACGiAQEAjwIAIaMBAQCPAgAhpAEBAI0CACELBAAAngIAIIoBAQCNAgAhjQFAAJACACGbAQEAjQIAIZwBCACaAgAhngEAAJsCngEioAEAAJwCoAEioQFAAJ0CACGiAQEAjwIAIaMBAQCPAgAhpAEBAI0CACELBAAAoAIAIIoBAQAAAAGNAUAAAAABmwEBAAAAAZwBCAAAAAGeAQAAAJ4BAqABAAAAoAECoQFAAAAAAaIBAQAAAAGjAQEAAAABpAEBAAAAAQkJAADNAgAgDQAAzgIAIIoBAQAAAAGNAUAAAAABoAEAAACpAQKmAUAAAAABpwFAAAAAAakBCAAAAAGqAQEAAAABAgAAAAUAIBsAALIDACADAAAABQAgGwAAsgMAIBwAALEDACABFAAAvwMAMA4DAAD8AQAgCQAAgwIAIA0AAPQBACCHAQAAhQIAMIgBAAADABCJAQAAhQIAMIoBAQAAAAGNAUAA6gEAIaABAACGAqkBIqYBQADqAQAhpwFAAOoBACGpAQgA9wEAIaoBAQDpAQAhqwEBAOgBACECAAAABQAgFAAAsQMAIAIAAACvAwAgFAAAsAMAIAuHAQAArgMAMIgBAACvAwAQiQEAAK4DADCKAQEA6AEAIY0BQADqAQAhoAEAAIYCqQEipgFAAOoBACGnAUAA6gEAIakBCAD3AQAhqgEBAOkBACGrAQEA6AEAIQuHAQAArgMAMIgBAACvAwAQiQEAAK4DADCKAQEA6AEAIY0BQADqAQAhoAEAAIYCqQEipgFAAOoBACGnAUAA6gEAIakBCAD3AQAhqgEBAOkBACGrAQEA6AEAIQeKAQEAjQIAIY0BQACQAgAhoAEAALACqQEipgFAAJACACGnAUAAkAIAIakBCACaAgAhqgEBAI8CACEJCQAAsgIAIA0AALMCACCKAQEAjQIAIY0BQACQAgAhoAEAALACqQEipgFAAJACACGnAUAAkAIAIakBCACaAgAhqgEBAI8CACEJCQAAzQIAIA0AAM4CACCKAQEAAAABjQFAAAAAAaABAAAAqQECpgFAAAAAAacBQAAAAAGpAQgAAAABqgEBAAAAAQQbAACnAwAwvwEAAKgDADDBAQAAqgMAIMUBAACrAwAwBBsAAJ4DADC_AQAAnwMAMMEBAAChAwAgxQEAALgCADAEGwAAlQMAML8BAACWAwAwwQEAAJgDACDFAQAA3QIAMAQbAACMAwAwvwEAAI0DADDBAQAAjwMAIMUBAAD6AgAwAAAABAMAALsDACAJAAC-AwAgDQAAuAMAIKoBAACHAgAgBQUAAIMDACAMAAC5AwAgDQAAuAMAIA4AALcDACC4AQAAhwIAIAUHAAC9AwAgCAAAuwMAIAkAAL4DACAMAAC5AwAgrgEAAIcCACACBQAAgwMAIK0BAACHAgAgAAeKAQEAAAABjQFAAAAAAaABAAAAqQECpgFAAAAAAacBQAAAAAGpAQgAAAABqgEBAAAAAQqKAQEAAAABjQFAAAAAAZsBAQAAAAGcAQgAAAABngEAAACeAQKgAQAAAKABAqEBQAAAAAGiAQEAAAABowEBAAAAAaQBAQAAAAEFigEBAAAAAYsBAgAAAAGMAQEAAAABjQFAAAAAAY4BAQAAAAEJigEBAAAAAY0BQAAAAAGlAQIAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEIAAAAAbABIAAAAAGxAQEAAAABCYoBAQAAAAGNAUAAAAABpQECAAAAAawBAQAAAAGtAQEAAAABrgEBAAAAAa8BCAAAAAGwASAAAAABsgEBAAAAAQsMAAC1AwAgDQAAtAMAIA4AALMDACCKAQEAAAABjQFAAAAAAawBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG6AQAAALoBArsBIAAAAAECAAAAAQAgGwAAxAMAIASKAQEAAAABjQFAAAAAAawBAQAAAAGtAQEAAAABAgAAADsAIBsAAMYDACADigEBAAAAAaQBAQAAAAGlAQIAAAABBYoBAQAAAAGLAQIAAAABjAEBAAAAAY0BQAAAAAGPAQEAAAABAwAAACUAIBsAAMQDACAcAADMAwAgDQAAACUAIAwAAIoDACANAACJAwAgDgAAiAMAIBQAAMwDACCKAQEAjQIAIY0BQACQAgAhrAEBAI0CACG2AQEAjQIAIbcBAQCNAgAhuAEBAI8CACG6AQAAhwO6ASK7ASAA1AIAIQsMAACKAwAgDQAAiQMAIA4AAIgDACCKAQEAjQIAIY0BQACQAgAhrAEBAI0CACG2AQEAjQIAIbcBAQCNAgAhuAEBAI8CACG6AQAAhwO6ASK7ASAA1AIAIQMAAAA-ACAbAADGAwAgHAAAzwMAIAYAAAA-ACAUAADPAwAgigEBAI0CACGNAUAAkAIAIawBAQCNAgAhrQEBAI8CACEEigEBAI0CACGNAUAAkAIAIawBAQCNAgAhrQEBAI8CACELBQAAtgMAIAwAALUDACANAAC0AwAgigEBAAAAAY0BQAAAAAGsAQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABugEAAAC6AQK7ASAAAAABAgAAAAEAIBsAANADACADigEBAAAAAY4BAQAAAAGlAQIAAAABCooBAQAAAAGNAUAAAAABjwEBAAAAAZsBAQAAAAGcAQgAAAABngEAAACeAQKgAQAAAKABAqEBQAAAAAGiAQEAAAABowEBAAAAAQMAAAAlACAbAADQAwAgHAAA1gMAIA0AAAAlACAFAACLAwAgDAAAigMAIA0AAIkDACAUAADWAwAgigEBAI0CACGNAUAAkAIAIawBAQCNAgAhtgEBAI0CACG3AQEAjQIAIbgBAQCPAgAhugEAAIcDugEiuwEgANQCACELBQAAiwMAIAwAAIoDACANAACJAwAgigEBAI0CACGNAUAAkAIAIawBAQCNAgAhtgEBAI0CACG3AQEAjQIAIbgBAQCPAgAhugEAAIcDugEiuwEgANQCACENBwAA7gIAIAgAAO8CACAMAADxAgAgigEBAAAAAY0BQAAAAAGlAQIAAAABrAEBAAAAAa0BAQAAAAGuAQEAAAABrwEIAAAAAbABIAAAAAGxAQEAAAABsgEBAAAAAQIAAAANACAbAADXAwAgCgMAAMwCACANAADOAgAgigEBAAAAAY0BQAAAAAGgAQAAAKkBAqYBQAAAAAGnAUAAAAABqQEIAAAAAaoBAQAAAAGrAQEAAAABAgAAAAUAIBsAANkDACADAAAACwAgGwAA1wMAIBwAAN0DACAPAAAACwAgBwAA1QIAIAgAANYCACAMAADYAgAgFAAA3QMAIIoBAQCNAgAhjQFAAJACACGlAQIAjgIAIawBAQCNAgAhrQEBAI0CACGuAQEAjwIAIa8BCACaAgAhsAEgANQCACGxAQEAjQIAIbIBAQCNAgAhDQcAANUCACAIAADWAgAgDAAA2AIAIIoBAQCNAgAhjQFAAJACACGlAQIAjgIAIawBAQCNAgAhrQEBAI0CACGuAQEAjwIAIa8BCACaAgAhsAEgANQCACGxAQEAjQIAIbIBAQCNAgAhAwAAAAMAIBsAANkDACAcAADgAwAgDAAAAAMAIAMAALECACANAACzAgAgFAAA4AMAIIoBAQCNAgAhjQFAAJACACGgAQAAsAKpASKmAUAAkAIAIacBQACQAgAhqQEIAJoCACGqAQEAjwIAIasBAQCNAgAhCgMAALECACANAACzAgAgigEBAI0CACGNAUAAkAIAIaABAACwAqkBIqYBQACQAgAhpwFAAJACACGpAQgAmgIAIaoBAQCPAgAhqwEBAI0CACELBQAAtgMAIAwAALUDACAOAACzAwAgigEBAAAAAY0BQAAAAAGsAQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABugEAAAC6AQK7ASAAAAABAgAAAAEAIBsAAOEDACAKAwAAzAIAIAkAAM0CACCKAQEAAAABjQFAAAAAAaABAAAAqQECpgFAAAAAAacBQAAAAAGpAQgAAAABqgEBAAAAAasBAQAAAAECAAAABQAgGwAA4wMAIAMAAAAlACAbAADhAwAgHAAA5wMAIA0AAAAlACAFAACLAwAgDAAAigMAIA4AAIgDACAUAADnAwAgigEBAI0CACGNAUAAkAIAIawBAQCNAgAhtgEBAI0CACG3AQEAjQIAIbgBAQCPAgAhugEAAIcDugEiuwEgANQCACELBQAAiwMAIAwAAIoDACAOAACIAwAgigEBAI0CACGNAUAAkAIAIawBAQCNAgAhtgEBAI0CACG3AQEAjQIAIbgBAQCPAgAhugEAAIcDugEiuwEgANQCACEDAAAAAwAgGwAA4wMAIBwAAOoDACAMAAAAAwAgAwAAsQIAIAkAALICACAUAADqAwAgigEBAI0CACGNAUAAkAIAIaABAACwAqkBIqYBQACQAgAhpwFAAJACACGpAQgAmgIAIaoBAQCPAgAhqwEBAI0CACEKAwAAsQIAIAkAALICACCKAQEAjQIAIY0BQACQAgAhoAEAALACqQEipgFAAJACACGnAUAAkAIAIakBCACaAgAhqgEBAI8CACGrAQEAjQIAIQsFAAC2AwAgDQAAtAMAIA4AALMDACCKAQEAAAABjQFAAAAAAawBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG6AQAAALoBArsBIAAAAAECAAAAAQAgGwAA6wMAIA0HAADuAgAgCAAA7wIAIAkAAPACACCKAQEAAAABjQFAAAAAAaUBAgAAAAGsAQEAAAABrQEBAAAAAa4BAQAAAAGvAQgAAAABsAEgAAAAAbEBAQAAAAGyAQEAAAABAgAAAA0AIBsAAO0DACADAAAAJQAgGwAA6wMAIBwAAPEDACANAAAAJQAgBQAAiwMAIA0AAIkDACAOAACIAwAgFAAA8QMAIIoBAQCNAgAhjQFAAJACACGsAQEAjQIAIbYBAQCNAgAhtwEBAI0CACG4AQEAjwIAIboBAACHA7oBIrsBIADUAgAhCwUAAIsDACANAACJAwAgDgAAiAMAIIoBAQCNAgAhjQFAAJACACGsAQEAjQIAIbYBAQCNAgAhtwEBAI0CACG4AQEAjwIAIboBAACHA7oBIrsBIADUAgAhAwAAAAsAIBsAAO0DACAcAAD0AwAgDwAAAAsAIAcAANUCACAIAADWAgAgCQAA1wIAIBQAAPQDACCKAQEAjQIAIY0BQACQAgAhpQECAI4CACGsAQEAjQIAIa0BAQCNAgAhrgEBAI8CACGvAQgAmgIAIbABIADUAgAhsQEBAI0CACGyAQEAjQIAIQ0HAADVAgAgCAAA1gIAIAkAANcCACCKAQEAjQIAIY0BQACQAgAhpQECAI4CACGsAQEAjQIAIa0BAQCNAgAhrgEBAI8CACGvAQgAmgIAIbABIADUAgAhsQEBAI0CACGyAQEAjQIAIQUFHwQGAAsMHgcNHQkOBgIEAwABBgAKCQoDDRoJAgQAAgoABAUGAAgHAAUIAAEJEAMMFAcCBQ4EBgAGAQUPAAIKAAQLAAECCRUADBYAAgQAAgsAAQIJGwANHAAEBSMADCIADSEADiAAAAAAAwYAECEAESIAEgAAAAMGABAhABEiABIAAAMGABchABgiABkAAAADBgAXIQAYIgAZAgcABQgAAQIHAAUIAAEFBgAeIQAhIgAiQwAfRAAgAAAAAAAFBgAeIQAhIgAiQwAfRAAgAQMAAQEDAAEFBgAnIQAqIgArQwAoRAApAAAAAAAFBgAnIQAqIgArQwAoRAApAgQAAgoABAIEAAIKAAQFBgAwIQAzIgA0QwAxRAAyAAAAAAAFBgAwIQAzIgA0QwAxRAAyAgQAAgsAAQIEAAILAAEFBgA5IQA8IgA9QwA6RAA7AAAAAAAFBgA5IQA8IgA9QwA6RAA7AgoABAsAAQIKAAQLAAEFBgBCIQBFIgBGQwBDRABEAAAAAAAFBgBCIQBFIgBGQwBDRABEDwIBECQBEScBEigBEykBFSsBFi0MFy4NGDABGTIMGjMOHTQBHjUBHzYMIzkPJDoTJTwFJj0FJ0AFKEEFKUIFKkQFK0YMLEcULUkFLksML0wVME0FMU4FMk8MM1IWNFMaNVQENlUEN1YEOFcEOVgEOloEO1wMPF0bPV8EPmEMP2IcQGMEQWQEQmUMRWgdRmkjR2oCSGsCSWwCSm0CS24CTHACTXIMTnMkT3UCUHcMUXglUnkCU3oCVHsMVX4mVn8sV4ABA1iBAQNZggEDWoMBA1uEAQNchgEDXYgBDF6JAS1fiwEDYI0BDGGOAS5ijwEDY5ABA2SRAQxllAEvZpUBNWeWAQlolwEJaZgBCWqZAQlrmgEJbJwBCW2eAQxunwE2b6EBCXCjAQxxpAE3cqUBCXOmAQl0pwEMdaoBOHarAT53rAEHeK0BB3muAQd6rwEHe7ABB3yyAQd9tAEMfrUBP3-3AQeAAbkBDIEBugFAggG7AQeDAbwBB4QBvQEMhQHAAUGGAcEBRw"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("node:buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/utils/prisma.ts
import { PrismaPg } from "@prisma/adapter-pg";
var url = new URL(process.env.DATABASE_URL);
var ssl = url.searchParams.get("sslmode") === "require" ? { rejectUnauthorized: false } : void 0;
var pool = new pg.Pool({
  host: url.hostname,
  port: parseInt(url.port || "5432"),
  database: url.pathname.slice(1).split("?")[0],
  user: url.username,
  password: url.password,
  ssl,
  max: 5
});
var adapter = new PrismaPg(pool);
var prisma = new PrismaClient({ adapter });

// src/config/index.ts
import dotenv from "dotenv";
dotenv.config();
var config2 = {
  port: parseInt(process.env.PORT || "5000"),
  jwtSecret: process.env.JWT_SECRET || "fallback-secret",
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || "7d",
  adminEmail: process.env.ADMIN_EMAIL || "admin@gearup.com",
  adminPassword: process.env.ADMIN_PASSWORD || "Admin@123",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY || "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || ""
};

// src/features/auth/auth.service.ts
var registerUser = async (data) => {
  const exists = await prisma.user.findUnique({ where: { email: data.email } });
  if (exists) throw new AppError("Email already registered", 409);
  const hashed = await bcrypt.hash(data.password, 12);
  const user = await prisma.user.create({
    data: { email: data.email, password: hashed, name: data.name, phone: data.phone, role: data.role },
    select: { id: true, email: true, name: true, phone: true, role: true, createdAt: true }
  });
  const token = jwt.sign({ userId: user.id, role: user.role }, config2.jwtSecret, { expiresIn: config2.jwtExpiresIn });
  return { user, token };
};
var loginUser = async (data) => {
  const user = await prisma.user.findUnique({ where: { email: data.email } });
  if (!user) throw new AppError("Invalid email or password", 401);
  if (!user.isActive) throw new AppError("Account is suspended", 403);
  const isValid = await bcrypt.compare(data.password, user.password);
  if (!isValid) throw new AppError("Invalid email or password", 401);
  const token = jwt.sign({ userId: user.id, role: user.role }, config2.jwtSecret, { expiresIn: config2.jwtExpiresIn });
  return {
    user: { id: user.id, email: user.email, name: user.name, phone: user.phone, role: user.role, createdAt: user.createdAt },
    token
  };
};
var getCurrentUser = async (userId) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, email: true, name: true, phone: true, role: true, isActive: true, createdAt: true }
  });
  if (!user) throw new AppError("User not found", 404);
  return user;
};
var updateProfile = async (userId, data) => {
  return prisma.user.update({
    where: { id: userId },
    data,
    select: { id: true, email: true, name: true, phone: true, role: true, isActive: true, createdAt: true }
  });
};
var updatePassword = async (userId, currentPassword, newPassword) => {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new AppError("User not found", 404);
  const isValid = await bcrypt.compare(currentPassword, user.password);
  if (!isValid) throw new AppError("Current password is incorrect", 400);
  const hashed = await bcrypt.hash(newPassword, 12);
  await prisma.user.update({ where: { id: userId }, data: { password: hashed } });
};

// src/features/auth/auth.controller.ts
var register = async (req, res, next) => {
  try {
    const parsed = registerSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const result = await registerUser(parsed.data);
    sendSuccess(res, result, "Registration successful", 201);
  } catch (err) {
    next(err);
  }
};
var login = async (req, res, next) => {
  try {
    const parsed = loginSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const result = await loginUser(parsed.data);
    sendSuccess(res, result, "Login successful");
  } catch (err) {
    next(err);
  }
};
var getMe = async (req, res, next) => {
  try {
    const user = await getCurrentUser(req.user.userId);
    sendSuccess(res, user);
  } catch (err) {
    next(err);
  }
};
var updateProfileHandler = async (req, res, next) => {
  try {
    const parsed = updateProfileSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const user = await updateProfile(req.user.userId, parsed.data);
    sendSuccess(res, user, "Profile updated");
  } catch (err) {
    next(err);
  }
};
var updatePasswordHandler = async (req, res, next) => {
  try {
    const parsed = updatePasswordSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    await updatePassword(req.user.userId, parsed.data.currentPassword, parsed.data.newPassword);
    sendSuccess(res, null, "Password updated");
  } catch (err) {
    next(err);
  }
};

// src/middleware/auth.ts
import jwt2 from "jsonwebtoken";
var authenticate = (req, res, next) => {
  const header = req.headers.authorization;
  if (!header?.startsWith("Bearer ")) {
    return res.status(401).json({ success: false, message: "No token provided" });
  }
  const token = header.split(" ")[1];
  try {
    const decoded = jwt2.verify(token, config2.jwtSecret);
    req.user = decoded;
    next();
  } catch {
    return res.status(401).json({ success: false, message: "Invalid or expired token" });
  }
};
var authorize = (...roles) => (req, res, next) => {
  if (!req.user || !roles.includes(req.user.role)) {
    return res.status(403).json({ success: false, message: "Insufficient permissions" });
  }
  next();
};

// src/features/auth/auth.routes.ts
var router = Router();
router.post("/register", register);
router.post("/login", login);
router.get("/me", authenticate, getMe);
router.put("/profile", authenticate, updateProfileHandler);
router.put("/password", authenticate, updatePasswordHandler);
var auth_routes_default = router;

// src/features/gear/gear.routes.ts
import { Router as Router2 } from "express";

// src/features/gear/gear.service.ts
var getGear = async (filters) => {
  const where = {};
  if (filters.category) where.categoryId = filters.category;
  if (filters.brand) where.brand = { contains: filters.brand, mode: "insensitive" };
  if (filters.search) {
    where.OR = [
      { name: { contains: filters.search, mode: "insensitive" } },
      { description: { contains: filters.search, mode: "insensitive" } }
    ];
  }
  if (filters.minPrice || filters.maxPrice) {
    where.pricePerDay = {};
    if (filters.minPrice) where.pricePerDay.gte = filters.minPrice;
    if (filters.maxPrice) where.pricePerDay.lte = filters.maxPrice;
  }
  if (filters.available === "true") where.available = true;
  return prisma.gearItem.findMany({
    where,
    include: { category: true, provider: { select: { id: true, name: true } } },
    orderBy: { createdAt: "desc" }
  });
};
var getGearById = (id) => prisma.gearItem.findUnique({
  where: { id },
  include: {
    category: true,
    provider: { select: { id: true, name: true, email: true } },
    reviews: { include: { user: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" } }
  }
});
var getCategories = () => prisma.category.findMany({ orderBy: { name: "asc" } });

// src/features/gear/gear.controller.ts
var browseGear = async (req, res, next) => {
  try {
    const gear = await getGear(req.query);
    sendSuccess(res, gear);
  } catch (err) {
    next(err);
  }
};
var getGearDetails = async (req, res, next) => {
  try {
    const gear = await getGearById(req.params.id);
    if (!gear) return sendError(res, "Gear not found", 404);
    sendSuccess(res, gear);
  } catch (err) {
    next(err);
  }
};
var listCategories = async (_req, res, next) => {
  try {
    const categories = await getCategories();
    sendSuccess(res, categories);
  } catch (err) {
    next(err);
  }
};

// src/features/gear/gear.routes.ts
var router2 = Router2();
router2.get("/", browseGear);
router2.get("/categories", listCategories);
router2.get("/:id", getGearDetails);
var gear_routes_default = router2;

// src/features/rental/rental.routes.ts
import { Router as Router3 } from "express";

// src/features/rental/rental.validation.ts
import { z as z2 } from "zod";
var createRentalSchema = z2.object({
  startDate: z2.string().datetime(),
  endDate: z2.string().datetime(),
  note: z2.string().optional(),
  items: z2.array(z2.object({
    gearItemId: z2.string().min(1),
    quantity: z2.number().int().positive()
  })).min(1)
});

// src/features/rental/rental.service.ts
var createRental = async (customerId, data) => {
  const start = new Date(data.startDate);
  const end = new Date(data.endDate);
  if (end <= start) throw new AppError("End date must be after start date", 400);
  let totalAmount = 0;
  const days = Math.ceil((end.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24));
  const rentalItems = [];
  for (const item of data.items) {
    const gear = await prisma.gearItem.findUnique({ where: { id: item.gearItemId } });
    if (!gear) throw new AppError(`Gear ${item.gearItemId} not found`, 404);
    if (!gear.available || gear.quantity < item.quantity) throw new AppError(`Insufficient stock: ${gear.name}`, 400);
    totalAmount += gear.pricePerDay * days * item.quantity;
    rentalItems.push({ gearItemId: item.gearItemId, quantity: item.quantity });
  }
  const rental = await prisma.$transaction(async (tx) => {
    for (const item of data.items) {
      await tx.gearItem.update({
        where: { id: item.gearItemId },
        data: { quantity: { decrement: item.quantity }, available: true }
      });
    }
    return tx.rentalOrder.create({
      data: {
        customerId,
        startDate: start,
        endDate: end,
        totalAmount,
        note: data.note,
        rentalItems: { create: rentalItems }
      },
      include: { rentalItems: { include: { gearItem: true } } }
    });
  });
  return rental;
};
var getUserRentals = (userId) => prisma.rentalOrder.findMany({
  where: { customerId: userId },
  include: { rentalItems: { include: { gearItem: true } }, payments: true },
  orderBy: { createdAt: "desc" }
});
var getRentalById = async (rentalId, userId, userRole) => {
  const rental = await prisma.rentalOrder.findUnique({
    where: { id: rentalId },
    include: { rentalItems: { include: { gearItem: true } }, payments: true, customer: { select: { id: true, name: true, email: true, phone: true } } }
  });
  if (!rental) throw new AppError("Rental order not found", 404);
  if (userRole === "CUSTOMER" && rental.customerId !== userId) throw new AppError("Not authorized", 403);
  return rental;
};
var cancelRental = async (rentalId, customerId) => {
  const rental = await prisma.rentalOrder.findUnique({ where: { id: rentalId } });
  if (!rental) throw new AppError("Rental order not found", 404);
  if (rental.customerId !== customerId) throw new AppError("Not authorized", 403);
  if (rental.status !== "PLACED") throw new AppError("Can only cancel PLACED orders", 400);
  const items = await prisma.rentalItem.findMany({ where: { rentalOrderId: rentalId } });
  return prisma.$transaction(async (tx) => {
    for (const item of items) {
      await tx.gearItem.update({
        where: { id: item.gearItemId },
        data: { quantity: { increment: item.quantity }, available: true }
      });
    }
    await tx.payment.updateMany({
      where: { rentalOrderId: rentalId },
      data: { status: "FAILED" }
    });
    return tx.rentalOrder.update({
      where: { id: rentalId },
      data: { status: "CANCELLED" },
      include: { rentalItems: { include: { gearItem: true } } }
    });
  });
};

// src/features/rental/rental.controller.ts
var createRental2 = async (req, res, next) => {
  try {
    const parsed = createRentalSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const rental = await createRental(req.user.userId, parsed.data);
    sendSuccess(res, rental, "Rental order created", 201);
  } catch (err) {
    next(err);
  }
};
var getUserRentals2 = async (req, res, next) => {
  try {
    const rentals = await getUserRentals(req.user.userId);
    sendSuccess(res, rentals);
  } catch (err) {
    next(err);
  }
};
var getRentalById2 = async (req, res, next) => {
  try {
    const rental = await getRentalById(req.params.id, req.user.userId, req.user.role);
    sendSuccess(res, rental);
  } catch (err) {
    next(err);
  }
};
var cancelRental2 = async (req, res, next) => {
  try {
    const rental = await cancelRental(req.params.id, req.user.userId);
    sendSuccess(res, rental, "Rental cancelled");
  } catch (err) {
    next(err);
  }
};

// src/features/rental/rental.routes.ts
var router3 = Router3();
router3.post("/", authenticate, createRental2);
router3.get("/", authenticate, getUserRentals2);
router3.get("/:id", authenticate, getRentalById2);
router3.post("/:id/cancel", authenticate, cancelRental2);
var rental_routes_default = router3;

// src/features/payment/payment.routes.ts
import { Router as Router4 } from "express";

// src/features/payment/payment.service.ts
import Stripe from "stripe";
var stripe = config2.stripeSecretKey ? new Stripe(config2.stripeSecretKey) : null;
var getUserPayments = (userId) => prisma.payment.findMany({
  where: { userId },
  include: { rentalOrder: { include: { rentalItems: { include: { gearItem: { select: { id: true, name: true } } } } } } },
  orderBy: { createdAt: "desc" }
});
var getPaymentById = async (paymentId, userId, userRole) => {
  const payment = await prisma.payment.findUnique({
    where: { id: paymentId },
    include: { rentalOrder: { include: { rentalItems: { include: { gearItem: true } } } } }
  });
  if (!payment) throw new AppError("Payment not found", 404);
  if (payment.userId !== userId && userRole === "CUSTOMER") throw new AppError("Not authorized", 403);
  return payment;
};
var createPaymentIntent = async (userId, rentalOrderId) => {
  if (!stripe) throw new AppError("Stripe is not configured", 500);
  const rental = await prisma.rentalOrder.findUnique({
    where: { id: rentalOrderId },
    include: { payments: true }
  });
  if (!rental) throw new AppError("Rental order not found", 404);
  if (rental.customerId !== userId) throw new AppError("Not authorized", 403);
  if (rental.status !== "CONFIRMED") throw new AppError("Order must be confirmed before payment", 400);
  const existingPayment = rental.payments.find((p) => p.status === "PENDING" || p.status === "COMPLETED");
  if (existingPayment) throw new AppError("Payment already exists for this order", 400);
  const amountInCents = Math.round(rental.totalAmount * 100);
  const paymentIntent = await stripe.paymentIntents.create({
    amount: amountInCents,
    currency: "usd",
    metadata: { rentalOrderId },
    automatic_payment_methods: { enabled: true, allow_redirects: "never" }
  });
  await prisma.payment.create({
    data: {
      transactionId: `pi-${paymentIntent.id}`,
      amount: rental.totalAmount,
      method: "STRIPE",
      status: "PENDING",
      stripePaymentIntentId: paymentIntent.id,
      stripeClientSecret: paymentIntent.client_secret,
      rentalOrderId,
      userId
    }
  });
  return { clientSecret: paymentIntent.client_secret, paymentIntentId: paymentIntent.id, amount: rental.totalAmount };
};
var confirmPayment = async (userId, paymentIntentId) => {
  const payment = await prisma.payment.findFirst({
    where: { stripePaymentIntentId: paymentIntentId },
    include: { rentalOrder: true }
  });
  if (!payment) throw new AppError("Payment not found", 404);
  if (payment.userId !== userId) throw new AppError("Not authorized", 403);
  if (stripe) {
    const intent = await stripe.paymentIntents.retrieve(paymentIntentId);
    if (intent.status !== "succeeded") throw new AppError(`Payment not completed. Status: ${intent.status}`, 400);
  }
  await prisma.$transaction(async (tx) => {
    await tx.payment.update({
      where: { id: payment.id },
      data: { status: "COMPLETED", paidAt: /* @__PURE__ */ new Date() }
    });
    await tx.rentalOrder.update({
      where: { id: payment.rentalOrderId },
      data: { status: "PAID" }
    });
  });
  return { paymentId: payment.id };
};
var handleStripeWebhook = async (rawBody, sig) => {
  if (!stripe) throw new AppError("Stripe is not configured", 500);
  let event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, sig, config2.stripeWebhookSecret);
  } catch {
    throw new AppError("Invalid webhook signature", 400);
  }
  if (event.type === "payment_intent.succeeded") {
    const paymentIntent = event.data.object;
    const payment = await prisma.payment.findFirst({ where: { stripePaymentIntentId: paymentIntent.id } });
    if (payment && payment.status === "PENDING") {
      await prisma.$transaction(async (tx) => {
        await tx.payment.update({
          where: { id: payment.id },
          data: { status: "COMPLETED", paidAt: /* @__PURE__ */ new Date() }
        });
        await tx.rentalOrder.update({
          where: { id: payment.rentalOrderId },
          data: { status: "PAID" }
        });
      });
    }
  }
  if (event.type === "payment_intent.payment_failed") {
    const paymentIntent = event.data.object;
    await prisma.payment.updateMany({
      where: { stripePaymentIntentId: paymentIntent.id },
      data: { status: "FAILED" }
    });
  }
  return { received: true };
};

// src/features/payment/payment.controller.ts
var getStripeConfig = (_req, res) => {
  sendSuccess(res, { publishableKey: config2.stripePublishableKey || null });
};
var getUserPayments2 = async (req, res, next) => {
  try {
    const payments = await getUserPayments(req.user.userId);
    sendSuccess(res, payments);
  } catch (err) {
    next(err);
  }
};
var getPaymentById2 = async (req, res, next) => {
  try {
    const payment = await getPaymentById(req.params.id, req.user.userId, req.user.role);
    sendSuccess(res, payment);
  } catch (err) {
    next(err);
  }
};
var createPaymentIntent2 = async (req, res, next) => {
  try {
    const { rentalOrderId } = req.body;
    if (!rentalOrderId) return sendError(res, "rentalOrderId is required", 400);
    const result = await createPaymentIntent(req.user.userId, rentalOrderId);
    sendSuccess(res, result, "Payment intent created");
  } catch (err) {
    next(err);
  }
};
var confirmPayment2 = async (req, res, next) => {
  try {
    const { paymentIntentId } = req.body;
    if (!paymentIntentId) return sendError(res, "paymentIntentId is required", 400);
    const result = await confirmPayment(req.user.userId, paymentIntentId);
    sendSuccess(res, result, "Payment confirmed");
  } catch (err) {
    next(err);
  }
};
var handleStripeWebhook2 = async (req, res, next) => {
  try {
    const sig = req.headers["stripe-signature"];
    if (!sig) return sendError(res, "Webhook signature missing", 400);
    if (!req.rawBody) return sendError(res, "Raw body not available", 400);
    const result = await handleStripeWebhook(req.rawBody, sig);
    res.json(result);
  } catch (err) {
    next(err);
  }
};

// src/features/payment/payment.routes.ts
var router4 = Router4();
router4.get("/config", getStripeConfig);
router4.post("/create", authenticate, createPaymentIntent2);
router4.post("/confirm", authenticate, confirmPayment2);
router4.post("/webhook", handleStripeWebhook2);
router4.get("/", authenticate, getUserPayments2);
router4.get("/:id", authenticate, getPaymentById2);
var payment_routes_default = router4;

// src/features/provider/provider.routes.ts
import { Router as Router5 } from "express";

// src/features/gear/gear.validation.ts
import { z as z3 } from "zod";
var createGearSchema = z3.object({
  name: z3.string().min(1),
  description: z3.string().min(1),
  brand: z3.string().optional(),
  pricePerDay: z3.number().positive(),
  quantity: z3.number().int().positive(),
  categoryId: z3.string().min(1)
});
var updateGearSchema = z3.object({
  name: z3.string().min(1).optional(),
  description: z3.string().optional(),
  brand: z3.string().optional(),
  pricePerDay: z3.number().positive().optional(),
  quantity: z3.number().int().positive().optional(),
  available: z3.boolean().optional()
});

// src/features/provider/provider.service.ts
var addGear = async (providerId, data) => {
  return prisma.gearItem.create({
    data: { ...data, providerId },
    include: { category: true }
  });
};
var updateGear = async (gearId, providerId, data) => {
  const gear = await prisma.gearItem.findUnique({ where: { id: gearId } });
  if (!gear) throw new AppError("Gear not found", 404);
  if (gear.providerId !== providerId) throw new AppError("Not authorized", 403);
  if (data.quantity !== void 0) {
    data.available = data.quantity > 0;
  }
  return prisma.gearItem.update({
    where: { id: gearId },
    data,
    include: { category: true }
  });
};
var deleteGear = async (gearId, providerId) => {
  const gear = await prisma.gearItem.findUnique({ where: { id: gearId } });
  if (!gear) throw new AppError("Gear not found", 404);
  if (gear.providerId !== providerId) throw new AppError("Not authorized", 403);
  await prisma.gearItem.delete({ where: { id: gearId } });
};
var getProviderOrders = async (providerId) => {
  const gearItems = await prisma.gearItem.findMany({ where: { providerId }, select: { id: true } });
  const gearIds = gearItems.map((g) => g.id);
  return prisma.rentalOrder.findMany({
    where: { rentalItems: { some: { gearItemId: { in: gearIds } } } },
    include: {
      rentalItems: { include: { gearItem: true } },
      customer: { select: { id: true, name: true, email: true, phone: true } },
      payments: true
    },
    orderBy: { createdAt: "desc" }
  });
};
var updateRentalStatus = async (rentalId, status, userId, userRole) => {
  const rental = await prisma.rentalOrder.findUnique({ where: { id: rentalId } });
  if (!rental) throw new AppError("Rental order not found", 404);
  if (userRole === "PROVIDER") {
    const providerGear = await prisma.gearItem.findMany({ where: { providerId: userId }, select: { id: true } });
    const gearIds = providerGear.map((g) => g.id);
    const itemCheck = await prisma.rentalItem.findFirst({ where: { rentalOrderId: rentalId, gearItemId: { in: gearIds } } });
    if (!itemCheck) throw new AppError("Not authorized to update this order", 403);
  }
  if (status === "RETURNED") {
    const items = await prisma.rentalItem.findMany({ where: { rentalOrderId: rentalId } });
    return prisma.$transaction(async (tx) => {
      for (const item of items) {
        await tx.gearItem.update({
          where: { id: item.gearItemId },
          data: { quantity: { increment: item.quantity }, available: true }
        });
      }
      return tx.rentalOrder.update({
        where: { id: rentalId },
        data: { status },
        include: { rentalItems: { include: { gearItem: true } }, customer: { select: { id: true, name: true, email: true } } }
      });
    });
  }
  return prisma.rentalOrder.update({
    where: { id: rentalId },
    data: { status },
    include: { rentalItems: { include: { gearItem: true } }, customer: { select: { id: true, name: true, email: true } } }
  });
};

// src/features/provider/provider.controller.ts
var addGear2 = async (req, res, next) => {
  try {
    const parsed = createGearSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const gear = await addGear(req.user.userId, parsed.data);
    sendSuccess(res, gear, "Gear added", 201);
  } catch (err) {
    next(err);
  }
};
var updateGear2 = async (req, res, next) => {
  try {
    const parsed = updateGearSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const gear = await updateGear(req.params.id, req.user.userId, parsed.data);
    sendSuccess(res, gear, "Gear updated");
  } catch (err) {
    next(err);
  }
};
var deleteGear2 = async (req, res, next) => {
  try {
    await deleteGear(req.params.id, req.user.userId);
    sendSuccess(res, null, "Gear deleted");
  } catch (err) {
    next(err);
  }
};
var getProviderOrders2 = async (req, res, next) => {
  try {
    const orders = await getProviderOrders(req.user.userId);
    sendSuccess(res, orders);
  } catch (err) {
    next(err);
  }
};
var updateRentalStatus2 = async (req, res, next) => {
  try {
    const { status } = req.body;
    if (!status) return sendError(res, "Status is required", 400);
    const rental = await updateRentalStatus(req.params.id, status, req.user.userId, req.user.role);
    sendSuccess(res, rental, "Status updated");
  } catch (err) {
    next(err);
  }
};

// src/features/provider/provider.routes.ts
var router5 = Router5();
router5.post("/gear", authenticate, authorize("PROVIDER"), addGear2);
router5.put("/gear/:id", authenticate, authorize("PROVIDER"), updateGear2);
router5.delete("/gear/:id", authenticate, authorize("PROVIDER"), deleteGear2);
router5.get("/orders", authenticate, authorize("PROVIDER"), getProviderOrders2);
router5.patch("/orders/:id", authenticate, authorize("PROVIDER"), updateRentalStatus2);
var provider_routes_default = router5;

// src/features/review/review.routes.ts
import { Router as Router6 } from "express";

// src/features/review/review.validation.ts
import { z as z4 } from "zod";
var createReviewSchema = z4.object({
  gearItemId: z4.string().min(1),
  rating: z4.number().int().min(1).max(5),
  comment: z4.string().optional()
});

// src/features/review/review.service.ts
var createReview = async (userId, data) => {
  const gear = await prisma.gearItem.findUnique({ where: { id: data.gearItemId } });
  if (!gear) throw new AppError("Gear not found", 404);
  const rental = await prisma.rentalOrder.findFirst({
    where: { customerId: userId, rentalItems: { some: { gearItemId: data.gearItemId } }, status: "RETURNED" }
  });
  if (!rental) throw new AppError("You must rent and return this gear before reviewing", 400);
  const existing = await prisma.review.findUnique({
    where: { userId_gearItemId: { userId, gearItemId: data.gearItemId } }
  });
  if (existing) throw new AppError("You already reviewed this gear", 409);
  return prisma.review.create({
    data: { ...data, userId },
    include: { user: { select: { id: true, name: true } } }
  });
};

// src/features/review/review.controller.ts
var createReview2 = async (req, res, next) => {
  try {
    const parsed = createReviewSchema.safeParse(req.body);
    if (!parsed.success) return sendError(res, "Validation failed", 400, parsed.error.flatten().fieldErrors);
    const review = await createReview(req.user.userId, parsed.data);
    sendSuccess(res, review, "Review created", 201);
  } catch (err) {
    next(err);
  }
};

// src/features/review/review.routes.ts
var router6 = Router6();
router6.post("/", authenticate, createReview2);
var review_routes_default = router6;

// src/features/admin/admin.routes.ts
import { Router as Router7 } from "express";

// src/features/admin/admin.service.ts
var getUsers = (role) => prisma.user.findMany({
  where: role ? { role } : {},
  select: { id: true, email: true, name: true, phone: true, role: true, isActive: true, createdAt: true },
  orderBy: { createdAt: "desc" }
});
var updateUserStatus = async (userId, isActive) => {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new AppError("User not found", 404);
  return prisma.user.update({ where: { id: userId }, data: { isActive }, select: { id: true, email: true, name: true, role: true, isActive: true } });
};
var getAllGear = () => prisma.gearItem.findMany({
  include: { category: true, provider: { select: { id: true, name: true, email: true } } },
  orderBy: { createdAt: "desc" }
});
var getAllRentals = () => prisma.rentalOrder.findMany({
  include: { rentalItems: { include: { gearItem: true } }, customer: { select: { id: true, name: true, email: true } }, payments: true },
  orderBy: { createdAt: "desc" }
});
var adminUpdateRentalStatus = async (rentalId, status) => {
  const rental = await prisma.rentalOrder.findUnique({ where: { id: rentalId } });
  if (!rental) throw new AppError("Rental order not found", 404);
  if (status === "RETURNED") {
    const items = await prisma.rentalItem.findMany({ where: { rentalOrderId: rentalId } });
    for (const item of items) {
      await prisma.gearItem.update({
        where: { id: item.gearItemId },
        data: { quantity: { increment: item.quantity }, available: true }
      });
    }
  }
  return prisma.rentalOrder.update({
    where: { id: rentalId },
    data: { status },
    include: { rentalItems: { include: { gearItem: true } }, customer: { select: { id: true, name: true, email: true } } }
  });
};
var createCategory = (data) => prisma.category.create({ data });
var updateCategory = async (id, data) => {
  const cat = await prisma.category.findUnique({ where: { id } });
  if (!cat) throw new AppError("Category not found", 404);
  return prisma.category.update({ where: { id }, data });
};
var deleteCategory = async (id) => {
  const cat = await prisma.category.findUnique({ where: { id } });
  if (!cat) throw new AppError("Category not found", 404);
  await prisma.category.delete({ where: { id } });
};

// src/features/admin/admin.controller.ts
var getUsers2 = async (req, res, next) => {
  try {
    const users = await getUsers(req.query.role);
    sendSuccess(res, users);
  } catch (err) {
    next(err);
  }
};
var updateUserStatus2 = async (req, res, next) => {
  try {
    const { isActive } = req.body;
    if (typeof isActive !== "boolean") return sendError(res, "isActive (boolean) is required", 400);
    const user = await updateUserStatus(req.params.id, isActive);
    sendSuccess(res, user, `User ${isActive ? "activated" : "suspended"}`);
  } catch (err) {
    next(err);
  }
};
var getAllGear2 = async (_req, res, next) => {
  try {
    const gear = await getAllGear();
    sendSuccess(res, gear);
  } catch (err) {
    next(err);
  }
};
var getAllRentals2 = async (_req, res, next) => {
  try {
    const rentals = await getAllRentals();
    sendSuccess(res, rentals);
  } catch (err) {
    next(err);
  }
};
var adminUpdateRentalStatus2 = async (req, res, next) => {
  try {
    const { status } = req.body;
    if (!status) return sendError(res, "Status is required", 400);
    const rental = await adminUpdateRentalStatus(req.params.id, status);
    sendSuccess(res, rental, "Status updated");
  } catch (err) {
    next(err);
  }
};
var createCategory2 = async (req, res, next) => {
  try {
    const { name, description } = req.body;
    if (!name) return sendError(res, "Name is required", 400);
    const cat = await createCategory({ name, description });
    sendSuccess(res, cat, "Category created", 201);
  } catch (err) {
    next(err);
  }
};
var updateCategory2 = async (req, res, next) => {
  try {
    const cat = await updateCategory(req.params.id, req.body);
    sendSuccess(res, cat, "Category updated");
  } catch (err) {
    next(err);
  }
};
var deleteCategory2 = async (req, res, next) => {
  try {
    await deleteCategory(req.params.id);
    sendSuccess(res, null, "Category deleted");
  } catch (err) {
    next(err);
  }
};

// src/features/admin/admin.routes.ts
var router7 = Router7();
router7.get("/users", authenticate, authorize("ADMIN"), getUsers2);
router7.patch("/users/:id", authenticate, authorize("ADMIN"), updateUserStatus2);
router7.get("/gear", authenticate, authorize("ADMIN"), getAllGear2);
router7.get("/rentals", authenticate, authorize("ADMIN"), getAllRentals2);
router7.patch("/rentals/:id", authenticate, authorize("ADMIN"), adminUpdateRentalStatus2);
router7.post("/categories", authenticate, authorize("ADMIN"), createCategory2);
router7.put("/categories/:id", authenticate, authorize("ADMIN"), updateCategory2);
router7.delete("/categories/:id", authenticate, authorize("ADMIN"), deleteCategory2);
var admin_routes_default = router7;

// src/app.ts
var app = express();
app.use(helmet());
app.use(cors());
app.use(morgan("dev"));
app.use(cookieParser());
app.use(express.json({
  limit: "10kb",
  verify: (req, _res, buf) => {
    req.rawBody = buf;
  }
}));
app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
app.use("/api/auth", auth_routes_default);
app.use("/api/gear", gear_routes_default);
app.get("/api/categories", listCategories);
app.use("/api/rentals", rental_routes_default);
app.use("/api/payments", payment_routes_default);
app.use("/api/provider", provider_routes_default);
app.use("/api/reviews", review_routes_default);
app.use("/api/admin", admin_routes_default);
app.all("/{*path}", (_req, res) => {
  res.status(404).json({ success: false, message: "Route not found" });
});
app.use(errorHandler);
var app_default = app;

// src/entry.ts
var entry_default = app_default;
export {
  entry_default as default
};
